citusmaster:
    image: dmitrievav/citus-rancher
    environment:
        CITUS_MASTER: true
    ports: ["5432:5432"]
    links:
        - citus
        - citus2

citus:
    image: dmitrievav/citus-rancher
    ports: ["5001:5432"]

citus2:
    image: dmitrievav/citus-rancher
    ports: ["5002:5432"]
